# Generated by Django 4.1.4 on 2023-09-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="surname",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
