# Generated by Django 4.1.4 on 2024-01-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_student_address_alter_student_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="social_url",
            field=models.URLField(null=True),
        ),
    ]
