# Generated by Django 4.1.4 on 2024-01-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_student_social_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="normalized_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
