# Generated by Django 4.1.4 on 2024-01-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_student_is_active_student_normalized_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
