# Generated by Django 5.0.1 on 2024-02-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_student_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="book",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.book"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.subject",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("students", models.ManyToManyField(to="home.student")),
            ],
        ),
    ]
