# Generated by Django 5.0.1 on 2024-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_book_subject_student_book_student_subject_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
