# Generated by Django 5.0.1 on 2024-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_book_id_alter_book_title_alter_student_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
