# Generated by Django 5.0.1 on 2024-02-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_book_id_alter_student_id_alter_subject_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="book",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                related_query_name="student",
                to="home.book",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                related_query_name="students",
                to="home.subject",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="students",
            field=models.ManyToManyField(
                related_name="teachers",
                related_query_name="teachers",
                to="home.student",
            ),
        ),
    ]
