# Generated by Django 5.0.1 on 2024-02-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_student_book_alter_student_subject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("buy", models.FloatField(null=True)),
                ("sale", models.FloatField(null=True)),
            ],
        ),
    ]
