# Generated by Django 5.0.1 on 2024-02-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="ccy",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
