# Generated by Django 5.0.1 on 2024-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_currency_ccy"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="picture",
            field=models.ImageField(null=True, upload_to="student_photos/"),
        ),
    ]
