# Generated by Django 5.0.1 on 2024-06-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_book_created_at_book_updated_at_student_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
